-- mock-data.sql
-- Large dataset seeding script with categories, users, recipes, ratings, and comments

PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

-- Wipe existing data in FK-safe order
DELETE FROM recipe_images;
DELETE FROM comments;
DELETE FROM ratings;
DELETE FROM recipes;
DELETE FROM users;
DELETE FROM categories;

-- Reset sequences (SQLite)
DELETE FROM sqlite_sequence WHERE name IN (
  'recipe_images','comments','ratings','recipes','users','categories'
);

-- Categories (rich set)
INSERT OR IGNORE INTO categories (name) VALUES
('Breakfast'),
('Brunch'),
('Lunch'),
('Dinner'),
('Dessert'),
('Snack'),
('Drink'),
('Vegan'),
('Vegetarian'),
('Gluten-Free'),
('Keto'),
('Paleo'),
('Seafood'),
('Italian'),
('Mexican'),
('Indian'),
('Chinese'),
('Japanese'),
('Mediterranean'),
('BBQ'),
('Soup'),
('Salad'),
('Baking'),
('Quick & Easy'),
('Slow Cooker'),
('Holiday'),
('Kids'),
('Low-Carb'),
('High-Protein'),
('Dairy-Free'),
('Nut-Free'),
('Uncategorized');

-- Users
INSERT INTO users (username, password) VALUES
('alice',            'password'),
('bob',              'password'),
('charlie',          'password'),
('diana',            'password'),
('edgar',            'password'),
('fiona',            'password'),
('george',           'password'),
('hannah',           'password'),
('ivan',             'password'),
('julia',            'password'),
('kevin',            'password'),
('linda',            'password'),
('matt',             'password'),
('nina',             'password'),
('oscar',            'password'),
('paula',            'password'),
('quentin',          'password'),
('rachel',           'password'),
('steve',            'password'),
('tina',             'password'),
('ulysses',          'password'),
('victoria',         'password'),
('walter',           'password'),
('yvonne',           'password'),
('zack',             'password');

-- Recipes
-- Use SELECT id FROM categories WHERE name = 'Name' for category_id association

INSERT INTO recipes (name, ingredients, directions, user_id, category_id) VALUES
('Classic Pancakes',
 'Flour; Milk; Eggs; Sugar; Baking powder; Salt; Butter',
 'Whisk dry ingredients; add milk and eggs; cook on griddle until bubbles form; flip and finish.',
 1, (SELECT id FROM categories WHERE name='Breakfast')),
('Avocado Toast Deluxe',
 'Bread; Avocado; Lemon; Chili flakes; Olive oil; Salt; Pepper',
 'Toast bread; mash avocado with lemon; spread; sprinkle chili, salt, pepper; drizzle oil.',
 2, (SELECT id FROM categories WHERE name='Brunch')),
('Grilled Chicken Salad',
 'Chicken breast; Lettuce; Tomato; Cucumber; Olive oil; Lemon; Salt; Pepper',
 'Grill seasoned chicken; chop veg; toss with dressing; slice chicken on top.',
 3, (SELECT id FROM categories WHERE name='Salad')),
('Spaghetti Carbonara',
 'Spaghetti; Eggs; Pancetta; Parmesan; Black pepper; Salt',
 'Cook pasta; crisp pancetta; temper eggs with pasta water; toss with pasta and cheese.',
 4, (SELECT id FROM categories WHERE name='Italian')),
('Veggie Stir-Fry',
 'Broccoli; Bell pepper; Carrot; Soy sauce; Garlic; Ginger; Sesame oil',
 'Stir-fry veg; add sauce; cook until crisp-tender; finish with sesame oil.',
 5, (SELECT id FROM categories WHERE name='Chinese')),
('Beef Tacos',
 'Tortillas; Ground beef; Taco seasoning; Lettuce; Tomato; Cheese',
 'Brown beef with seasoning; assemble tacos with toppings.',
 6, (SELECT id FROM categories WHERE name='Mexican')),
('Margherita Pizza',
 'Pizza dough; Tomato sauce; Mozzarella; Basil; Olive oil; Salt',
 'Stretch dough; add sauce, cheese; bake hot; finish with basil and oil.',
 7, (SELECT id FROM categories WHERE name='Italian')),
('Chocolate Chip Cookies',
 'Flour; Butter; Sugar; Brown sugar; Eggs; Vanilla; Chocolate chips; Baking soda; Salt',
 'Cream butter and sugars; add eggs and vanilla; fold dry; bake until edges set.',
 8, (SELECT id FROM categories WHERE name='Baking')),
('Berry Smoothie',
 'Mixed berries; Banana; Yogurt; Honey; Ice',
 'Blend until smooth; serve cold.',
 9, (SELECT id FROM categories WHERE name='Drink')),
('Keto Cauliflower Rice Bowl',
 'Cauliflower; Chicken; Avocado; Lime; Cilantro; Salt; Pepper',
 'Pulse cauliflower; sauté; top with chicken and avocado; season with lime and cilantro.',
 10, (SELECT id FROM categories WHERE name='Keto')),
('Vegan Buddha Bowl',
 'Quinoa; Chickpeas; Sweet potato; Spinach; Tahini; Lemon; Garlic',
 'Roast sweet potato; cook quinoa; assemble bowl; drizzle tahini dressing.',
 11, (SELECT id FROM categories WHERE name='Vegan')),
('Gluten-Free Banana Bread',
 'GF flour; Bananas; Eggs; Sugar; Butter; Baking soda; Salt; Vanilla',
 'Mash bananas; mix wet and dry; bake until toothpick clean.',
 12, (SELECT id FROM categories WHERE name='Gluten-Free')),
('BBQ Ribs',
 'Pork ribs; BBQ rub; BBQ sauce',
 'Season ribs; slow-cook until tender; glaze with sauce and finish on grill.',
 13, (SELECT id FROM categories WHERE name='BBQ')),
('Miso Ramen',
 'Ramen noodles; Miso; Broth; Scallions; Egg; Nori',
 'Simmer broth with miso; cook noodles; assemble with toppings.',
 14, (SELECT id FROM categories WHERE name='Japanese')),
('Butter Chicken',
 'Chicken; Butter; Tomato puree; Cream; Garam masala; Garlic; Ginger',
 'Marinate; cook sauce; simmer chicken in sauce until tender.',
 15, (SELECT id FROM categories WHERE name='Indian')),
('Mediterranean Grain Bowl',
 'Farro; Cucumber; Tomato; Olives; Feta; Lemon; Olive oil; Oregano',
 'Cook farro; chop veg; toss with dressing and feta.',
 16, (SELECT id FROM categories WHERE name='Mediterranean')),
('Clam Chowder',
 'Clams; Potatoes; Onion; Celery; Bacon; Cream; Butter; Flour',
 'Cook bacon; sauté veg; add clams and potatoes; thicken with roux; add cream.',
 17, (SELECT id FROM categories WHERE name='Soup')),
('Caprese Salad',
 'Tomato; Mozzarella; Basil; Olive oil; Balsamic; Salt; Pepper',
 'Layer tomato and mozzarella; top with basil; drizzle oil and balsamic.',
 18, (SELECT id FROM categories WHERE name='Salad')),
('Overnight Oats',
 'Oats; Milk; Chia seeds; Honey; Berries',
 'Combine ingredients; refrigerate overnight.',
 19, (SELECT id FROM categories WHERE name='Breakfast')),
('Green Detox Juice',
 'Kale; Cucumber; Apple; Lemon; Ginger; Water',
 'Blend and strain if desired.',
 20, (SELECT id FROM categories WHERE name='Drink')),
('Pulled Pork (Slow Cooker)',
 'Pork shoulder; Onion; Garlic; BBQ sauce; Apple cider vinegar; Spices',
 'Place all in slow cooker; cook low until pull-apart tender.',
 21, (SELECT id FROM categories WHERE name='Slow Cooker')),
('Grilled Salmon with Lemon',
 'Salmon; Lemon; Dill; Olive oil; Salt; Pepper',
 'Season salmon; grill; finish with lemon and dill.',
 22, (SELECT id FROM categories WHERE name='Seafood')),
('Tofu Teriyaki',
 'Tofu; Soy sauce; Mirin; Sugar; Garlic; Ginger; Scallions',
 'Pan-fry tofu; reduce teriyaki sauce; glaze tofu; top with scallions.',
 23, (SELECT id FROM categories WHERE name='Vegetarian')),
('Paleo Lettuce Wraps',
 'Ground turkey; Lettuce; Coconut aminos; Garlic; Ginger; Water chestnuts',
 'Sauté turkey; add aromatics and aminos; serve in lettuce cups.',
 24, (SELECT id FROM categories WHERE name='Paleo')),
('Holiday Roast Turkey',
 'Turkey; Butter; Herbs; Garlic; Salt; Pepper',
 'Season turkey; roast until internal temp reached; rest before carving.',
 25, (SELECT id FROM categories WHERE name='Holiday')),
('Mac and Cheese',
 'Macaroni; Cheddar; Milk; Butter; Flour; Salt; Pepper',
 'Cook pasta; make roux and cheese sauce; combine and bake.',
 1, (SELECT id FROM categories WHERE name='Baking')),
('Chicken Noodle Soup',
 'Chicken; Noodles; Carrots; Celery; Onion; Broth; Parsley',
 'Simmer chicken and veg; add noodles; season and finish with parsley.',
 2, (SELECT id FROM categories WHERE name='Soup')),
('Chocolate Mousse',
 'Chocolate; Eggs; Sugar; Cream; Vanilla; Salt',
 'Melt chocolate; fold with whipped cream and egg mixture; chill.',
 3, (SELECT id FROM categories WHERE name='Dessert')),
('Guacamole',
 'Avocado; Lime; Onion; Tomato; Cilantro; Salt; Jalapeño',
 'Mash avocado; fold in chopped ingredients; season to taste.',
 4, (SELECT id FROM categories WHERE name='Snack')),
('Iced Coffee',
 'Coffee; Ice; Milk; Sugar',
 'Brew strong coffee; cool; pour over ice with milk and sugar.',
 5, (SELECT id FROM categories WHERE name='Drink')),
('Sourdough Bread',
 'Sourdough starter; Flour; Water; Salt',
 'Mix and bulk ferment; shape; proof; bake with steam.',
 6, (SELECT id FROM categories WHERE name='Baking')),
('Chicken Caesar Wrap',
 'Tortilla; Chicken; Romaine; Parmesan; Caesar dressing',
 'Toss filling; wrap tightly and slice.',
 7, (SELECT id FROM categories WHERE name='Lunch')),
('Shrimp Scampi',
 'Shrimp; Garlic; Butter; Lemon; Parsley; Pasta',
 'Sauté garlic in butter; cook shrimp; toss with pasta and lemon.',
 8, (SELECT id FROM categories WHERE name='Seafood')),
('Falafel Pita',
 'Chickpeas; Onion; Garlic; Herbs; Spices; Pita; Tahini',
 'Blend and form; fry falafel; serve in pita with tahini.',
 9, (SELECT id FROM categories WHERE name='Mediterranean')),
('Beef Pho',
 'Beef bones; Spices; Rice noodles; Beef; Herbs; Lime',
 'Simmer aromatic broth; cook noodles; assemble with thin-sliced beef.',
 10, (SELECT id FROM categories WHERE name='Dinner')),
('Quinoa Stuffed Peppers',
 'Bell peppers; Quinoa; Black beans; Corn; Cheese; Spices',
 'Cook quinoa; mix filling; stuff peppers; bake with cheese.',
 11, (SELECT id FROM categories WHERE name='Vegetarian')),
('Protein Power Bowl',
 'Brown rice; Chicken; Broccoli; Egg; Sesame seeds; Soy sauce',
 'Cook ingredients; assemble bowl; drizzle soy sauce.',
 12, (SELECT id FROM categories WHERE name='High-Protein')),
('Almond Flour Brownies',
 'Almond flour; Cocoa; Eggs; Sugar; Butter; Vanilla; Salt',
 'Mix and bake until set.',
 13, (SELECT id FROM categories WHERE name='Dairy-Free')),
('Peanut-Free Trail Mix',
 'Pumpkin seeds; Sunflower seeds; Raisins; Chocolate chips; Pretzels',
 'Combine ingredients; portion into bags.',
 14, (SELECT id FROM categories WHERE name='Nut-Free')),
('Zucchini Noodles Pesto',
 'Zucchini; Basil; Parmesan; Pine nuts; Garlic; Olive oil; Lemon',
 'Spiralize zucchini; toss with pesto; serve immediately.',
 15, (SELECT id FROM categories WHERE name='Low-Carb')),
('French Toast',
 'Bread; Eggs; Milk; Cinnamon; Vanilla; Butter; Syrup',
 'Dip bread in custard; cook on buttered griddle; serve with syrup.',
 16, (SELECT id FROM categories WHERE name='Breakfast')),
('Mango Lassi',
 'Mango; Yogurt; Milk; Sugar; Cardamom',
 'Blend until smooth; serve chilled.',
 17, (SELECT id FROM categories WHERE name='Drink')),
('Baked Salmon Teriyaki',
 'Salmon; Soy sauce; Mirin; Sugar; Ginger; Garlic',
 'Marinate salmon; bake until flaky; reduce sauce to glaze.',
 18, (SELECT id FROM categories WHERE name='Japanese')),
('Chili Con Carne',
 'Ground beef; Beans; Tomato; Onion; Chili powder; Cumin; Garlic',
 'Brown beef; simmer with spices and beans until thick.',
 19, (SELECT id FROM categories WHERE name='Dinner')),
('Greek Yogurt Parfait',
 'Greek yogurt; Granola; Honey; Berries',
 'Layer ingredients in glass; drizzle honey.',
 20, (SELECT id FROM categories WHERE name='Snack'));

-- Ratings (use recipe name to resolve recipe_id)
INSERT INTO ratings (rating, recipe_id, user_id) VALUES
(5, (SELECT id FROM recipes WHERE name='Classic Pancakes'), 2),
(4, (SELECT id FROM recipes WHERE name='Classic Pancakes'), 3),
(5, (SELECT id FROM recipes WHERE name='Avocado Toast Deluxe'), 4),
(3, (SELECT id FROM recipes WHERE name='Avocado Toast Deluxe'), 1),
(4, (SELECT id FROM recipes WHERE name='Grilled Chicken Salad'), 5),
(5, (SELECT id FROM recipes WHERE name='Spaghetti Carbonara'), 6),
(4, (SELECT id FROM recipes WHERE name='Spaghetti Carbonara'), 7),
(5, (SELECT id FROM recipes WHERE name='Veggie Stir-Fry'), 8),
(5, (SELECT id FROM recipes WHERE name='Beef Tacos'), 9),
(4, (SELECT id FROM recipes WHERE name='Margherita Pizza'), 10),
(5, (SELECT id FROM recipes WHERE name='Chocolate Chip Cookies'), 11),
(4, (SELECT id FROM recipes WHERE name='Berry Smoothie'), 12),
(5, (SELECT id FROM recipes WHERE name='Keto Cauliflower Rice Bowl'), 13),
(4, (SELECT id FROM recipes WHERE name='Vegan Buddha Bowl'), 14),
(5, (SELECT id FROM recipes WHERE name='Gluten-Free Banana Bread'), 15),
(5, (SELECT id FROM recipes WHERE name='BBQ Ribs'), 16),
(4, (SELECT id FROM recipes WHERE name='Miso Ramen'), 17),
(5, (SELECT id FROM recipes WHERE name='Butter Chicken'), 18),
(5, (SELECT id FROM recipes WHERE name='Mediterranean Grain Bowl'), 19),
(3, (SELECT id FROM recipes WHERE name='Clam Chowder'), 20),
(4, (SELECT id FROM recipes WHERE name='Caprese Salad'), 21),
(5, (SELECT id FROM recipes WHERE name='Overnight Oats'), 22),
(4, (SELECT id FROM recipes WHERE name='Green Detox Juice'), 23),
(5, (SELECT id FROM recipes WHERE name='Pulled Pork (Slow Cooker)'), 24),
(5, (SELECT id FROM recipes WHERE name='Grilled Salmon with Lemon'), 25),
(4, (SELECT id FROM recipes WHERE name='Tofu Teriyaki'), 1),
(5, (SELECT id FROM recipes WHERE name='Paleo Lettuce Wraps'), 2),
(4, (SELECT id FROM recipes WHERE name='Holiday Roast Turkey'), 3),
(5, (SELECT id FROM recipes WHERE name='Mac and Cheese'), 4),
(4, (SELECT id FROM recipes WHERE name='Chicken Noodle Soup'), 5),
(5, (SELECT id FROM recipes WHERE name='Chocolate Mousse'), 6),
(4, (SELECT id FROM recipes WHERE name='Guacamole'), 7),
(3, (SELECT id FROM recipes WHERE name='Iced Coffee'), 8),
(5, (SELECT id FROM recipes WHERE name='Sourdough Bread'), 9),
(4, (SELECT id FROM recipes WHERE name='Chicken Caesar Wrap'), 10),
(5, (SELECT id FROM recipes WHERE name='Shrimp Scampi'), 11),
(5, (SELECT id FROM recipes WHERE name='Falafel Pita'), 12),
(4, (SELECT id FROM recipes WHERE name='Beef Pho'), 13),
(5, (SELECT id FROM recipes WHERE name='Quinoa Stuffed Peppers'), 14),
(5, (SELECT id FROM recipes WHERE name='Protein Power Bowl'), 15),
(4, (SELECT id FROM recipes WHERE name='Almond Flour Brownies'), 16),
(4, (SELECT id FROM recipes WHERE name='Peanut-Free Trail Mix'), 17),
(5, (SELECT id FROM recipes WHERE name='Zucchini Noodles Pesto'), 18),
(5, (SELECT id FROM recipes WHERE name='French Toast'), 19),
(4, (SELECT id FROM recipes WHERE name='Mango Lassi'), 20),
(5, (SELECT id FROM recipes WHERE name='Baked Salmon Teriyaki'), 21),
(4, (SELECT id FROM recipes WHERE name='Chili Con Carne'), 22),
(5, (SELECT id FROM recipes WHERE name='Greek Yogurt Parfait'), 23),

-- Additional ratings for variety
(5, (SELECT id FROM recipes WHERE name='Spaghetti Carbonara'), 2),
(3, (SELECT id FROM recipes WHERE name='Veggie Stir-Fry'), 3),
(5, (SELECT id FROM recipes WHERE name='BBQ Ribs'), 4),
(4, (SELECT id FROM recipes WHERE name='Butter Chicken'), 5),
(5, (SELECT id FROM recipes WHERE name='Shrimp Scampi'), 6),
(4, (SELECT id FROM recipes WHERE name='Falafel Pita'), 7),
(5, (SELECT id FROM recipes WHERE name='Sourdough Bread'), 8),
(4, (SELECT id FROM recipes WHERE name='Mac and Cheese'), 9),
(5, (SELECT id FROM recipes WHERE name='Quinoa Stuffed Peppers'), 10),
(4, (SELECT id FROM recipes WHERE name='Protein Power Bowl'), 11),
(5, (SELECT id FROM recipes WHERE name='French Toast'), 12),
(4, (SELECT id FROM recipes WHERE name='Chocolate Chip Cookies'), 13),
(5, (SELECT id FROM recipes WHERE name='Mediterranean Grain Bowl'), 14),
(4, (SELECT id FROM recipes WHERE name='Clam Chowder'), 15),
(5, (SELECT id FROM recipes WHERE name='Grilled Salmon with Lemon'), 16),
(4, (SELECT id FROM recipes WHERE name='Keto Cauliflower Rice Bowl'), 17),
(5, (SELECT id FROM recipes WHERE name='Vegan Buddha Bowl'), 18),
(4, (SELECT id FROM recipes WHERE name='Miso Ramen'), 19),
(5, (SELECT id FROM recipes WHERE name='Margherita Pizza'), 20);

-- Comments (use recipe name to resolve recipe_id)
INSERT INTO comments (content, recipe_id, user_id) VALUES
('These pancakes are so fluffy!', (SELECT id FROM recipes WHERE name='Classic Pancakes'), 5),
('I added blueberries—amazing.', (SELECT id FROM recipes WHERE name='Classic Pancakes'), 7),
('Love the chili flakes kick.', (SELECT id FROM recipes WHERE name='Avocado Toast Deluxe'), 6),
('Perfect quick lunch idea.', (SELECT id FROM recipes WHERE name='Grilled Chicken Salad'), 2),
('So creamy and delicious!', (SELECT id FROM recipes WHERE name='Spaghetti Carbonara'), 3),
('Great weeknight stir-fry.', (SELECT id FROM recipes WHERE name='Veggie Stir-Fry'), 8),
('Family taco night hit!', (SELECT id FROM recipes WHERE name='Beef Tacos'), 9),
('Crispy crust, yum.', (SELECT id FROM recipes WHERE name='Margherita Pizza'), 10),
('Chewy centers every time.', (SELECT id FROM recipes WHERE name='Chocolate Chip Cookies'), 11),
('Refreshing post-workout.', (SELECT id FROM recipes WHERE name='Berry Smoothie'), 12),
('Low-carb and tasty!', (SELECT id FROM recipes WHERE name='Keto Cauliflower Rice Bowl'), 13),
('Great tahini dressing.', (SELECT id FROM recipes WHERE name='Vegan Buddha Bowl'), 14),
('Moist and flavorful.', (SELECT id FROM recipes WHERE name='Gluten-Free Banana Bread'), 15),
('Fall-off-the-bone!', (SELECT id FROM recipes WHERE name='BBQ Ribs'), 16),
('Broth is umami-rich.', (SELECT id FROM recipes WHERE name='Miso Ramen'), 17),
('Restaurant quality.', (SELECT id FROM recipes WHERE name='Butter Chicken'), 18),
('Bright and herby.', (SELECT id FROM recipes WHERE name='Mediterranean Grain Bowl'), 19),
('Comfort in a bowl.', (SELECT id FROM recipes WHERE name='Clam Chowder'), 20),
('Simple and elegant.', (SELECT id FROM recipes WHERE name='Caprese Salad'), 21),
('So easy for mornings.', (SELECT id FROM recipes WHERE name='Overnight Oats'), 22),
('Nice zing from ginger.', (SELECT id FROM recipes WHERE name='Green Detox Juice'), 23),
('Set and forget—love it.', (SELECT id FROM recipes WHERE name='Pulled Pork (Slow Cooker)'), 24),
('Dill with lemon = perfect.', (SELECT id FROM recipes WHERE name='Grilled Salmon with Lemon'), 25),
('Sauce caramelized nicely.', (SELECT id FROM recipes WHERE name='Tofu Teriyaki'), 1),
('Super crisp lettuce cups!', (SELECT id FROM recipes WHERE name='Paleo Lettuce Wraps'), 2),
('Holiday staple now.', (SELECT id FROM recipes WHERE name='Holiday Roast Turkey'), 3),
('Ultra creamy!', (SELECT id FROM recipes WHERE name='Mac and Cheese'), 4),
('Great when sick.', (SELECT id FROM recipes WHERE name='Chicken Noodle Soup'), 5),
('So decadent.', (SELECT id FROM recipes WHERE name='Chocolate Mousse'), 6),
('Lime really pops.', (SELECT id FROM recipes WHERE name='Guacamole'), 7),
('Summer essential.', (SELECT id FROM recipes WHERE name='Iced Coffee'), 8),
('Crust is phenomenal.', (SELECT id FROM recipes WHERE name='Sourdough Bread'), 9),
('Perfect meal prep.', (SELECT id FROM recipes WHERE name='Chicken Caesar Wrap'), 10),
('Garlic butter heaven.', (SELECT id FROM recipes WHERE name='Shrimp Scampi'), 11),
('Crisp and fluffy pita.', (SELECT id FROM recipes WHERE name='Falafel Pita'), 12),
('Aromatic broth!', (SELECT id FROM recipes WHERE name='Beef Pho'), 13),
('Kid approved!', (SELECT id FROM recipes WHERE name='Quinoa Stuffed Peppers'), 14),
('Great post-gym bowl.', (SELECT id FROM recipes WHERE name='Protein Power Bowl'), 15),
('Fudgy without flour!', (SELECT id FROM recipes WHERE name='Almond Flour Brownies'), 16),
('School-safe snack.', (SELECT id FROM recipes WHERE name='Peanut-Free Trail Mix'), 17),
('Zoodles for the win.', (SELECT id FROM recipes WHERE name='Zucchini Noodles Pesto'), 18),
('Weekend favorite.', (SELECT id FROM recipes WHERE name='French Toast'), 19),
('So refreshing!', (SELECT id FROM recipes WHERE name='Mango Lassi'), 20),
('Sweet-savory balance.', (SELECT id FROM recipes WHERE name='Baked Salmon Teriyaki'), 21),
('Great with cornbread.', (SELECT id FROM recipes WHERE name='Chili Con Carne'), 22),
('Perfect snack cup.', (SELECT id FROM recipes WHERE name='Greek Yogurt Parfait'), 23),

-- More comments to enlarge dataset
('My kids loved these.', (SELECT id FROM recipes WHERE name='Chocolate Chip Cookies'), 4),
('Added spinach—great!', (SELECT id FROM recipes WHERE name='Veggie Stir-Fry'), 5),
('Extra lime did it.', (SELECT id FROM recipes WHERE name='Guacamole'), 6),
('Made it lactose-free.', (SELECT id FROM recipes WHERE name='Mac and Cheese'), 7),
('Meal-prep friendly.', (SELECT id FROM recipes WHERE name='Protein Power Bowl'), 8),
('Bread rose beautifully.', (SELECT id FROM recipes WHERE name='Sourdough Bread'), 12),
('Nice spice level.', (SELECT id FROM recipes WHERE name='Chili Con Carne'), 14),
('Roast came out juicy.', (SELECT id FROM recipes WHERE name='Holiday Roast Turkey'), 15),
('Perfect brunch.', (SELECT id FROM recipes WHERE name='Avocado Toast Deluxe'), 16),
('Dressing is spot on.', (SELECT id FROM recipes WHERE name='Grilled Chicken Salad'), 20);

COMMIT;